Traceback (most recent call last):
  File "/usr/local/bin/dpckan", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dpckan/update_dataset.py", line 21, in update_cli
    update(
  File "/usr/local/lib/python3.9/site-packages/dpckan/update_dataset.py", line 13, in update
    dataset_update(ckan_instance, package, datastore, exit_code)
  File "/usr/local/lib/python3.9/site-packages/dpckan/functions.py", line 136, in dataset_update
    different_resources = dataset_diff(ckan_instance, datapackage)
  File "/usr/local/lib/python3.9/site-packages/dpckan/functions.py", line 167, in dataset_diff
    resource_diff = get_resource_diff(ckan_instance, datapackage, resource_name, resource_id)
  File "/usr/local/lib/python3.9/site-packages/dpckan/functions.py", line 190, in get_resource_diff
    resource_diff['data_diff'] = is_resource_data_diff(ckan_instance,
  File "/usr/local/lib/python3.9/site-packages/dpckan/functions.py", line 205, in is_resource_data_diff
    ckan_data_hash = resource_url_hash(ckan_instance, resource_id)
  File "/usr/local/lib/python3.9/site-packages/dpckan/functions.py", line 257, in resource_url_hash
    resource_content = urlopen(ckan_datapackage_resource['url']).read()
  File "/usr/local/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
