{
  "version": "4.38.0",
  "time": 410.237,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "db6ba03f5e880efd93bb9e07294c706a",
          "bytes": 58451856,
          "fields": 27,
          "rows": 1918732
        }
      },
      "time": 410.237,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "327",
            "19602",
            "37749",
            "386023",
            "79193",
            "480",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "1000.0000",
            "0.2900",
            "290.00",
            "0.2900",
            "290.00",
            "290.00"
          ],
          "rowNumber": 1913327,
          "rowPosition": 1913328,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913328\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "236",
            "2775",
            "2782",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "1300.0000",
            "3.2000",
            "4160.00",
            "3.2000",
            "4160.00",
            "4160.00"
          ],
          "rowNumber": 1913328,
          "rowPosition": 1913329,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913329\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "327",
            "15104",
            "104458",
            "386023",
            "79193",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "25.0000",
            "128.7800",
            "3219.50",
            "128.7800",
            "3219.50",
            "3219.50"
          ],
          "rowNumber": 1913329,
          "rowPosition": 1913330,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913330\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "327",
            "4759",
            "119605",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "15.0000",
            "135.0000",
            "2025.00",
            "135.0000",
            "2025.00",
            "2025.00"
          ],
          "rowNumber": 1913330,
          "rowPosition": 1913331,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913331\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "100",
            "13962",
            "24783",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "2000.0000",
            "1.0000",
            "2000.00",
            "1.0000",
            "2000.00",
            "2000.00"
          ],
          "rowNumber": 1913331,
          "rowPosition": 1913332,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913332\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "100",
            "11434",
            "28199",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "100.0000",
            "10.0000",
            "1000.00",
            "10.0000",
            "1000.00",
            "1000.00"
          ],
          "rowNumber": 1913332,
          "rowPosition": 1913333,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913333\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "219",
            "12158",
            "269538",
            "386023",
            "79193",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "100.0000",
            "1.5000",
            "150.00",
            "1.5000",
            "150.00",
            "150.00"
          ],
          "rowNumber": 1913333,
          "rowPosition": 1913334,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913334\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "236",
            "16967",
            "39577",
            "386023",
            "79193",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "50.0000",
            "1.3700",
            "68.50",
            "1.3700",
            "68.50",
            "68.50"
          ],
          "rowNumber": 1913334,
          "rowPosition": 1913335,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913335\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "236",
            "17323",
            "67103",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "2000.0000",
            "4.0000",
            "8000.00",
            "4.0000",
            "8000.00",
            "8000.00"
          ],
          "rowNumber": 1913335,
          "rowPosition": 1913336,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913336\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "73146",
            "1",
            "32",
            "100",
            "9134",
            "40744",
            "386023",
            "79192",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "100.0000",
            "0.3900",
            "39.00",
            "0.3900",
            "39.00",
            "39.00"
          ],
          "rowNumber": 1913336,
          "rowPosition": 1913337,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913337\" violates the foreign key: for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "236",
            "21588",
            "170123",
            "386023",
            "79193",
            "1071",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "45.0000",
            "52.5600",
            "2365.20",
            "52.5600",
            "2365.20",
            "2365.20"
          ],
          "rowNumber": 1913337,
          "rowPosition": 1913338,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913338\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "73146",
            "1",
            "32",
            "100",
            "3702",
            "86804",
            "386023",
            "79192",
            "480",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "20000.0000",
            "0.0400",
            "800.00",
            "0.0400",
            "800.00",
            "800.00"
          ],
          "rowNumber": 1913338,
          "rowPosition": 1913339,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913339\" violates the foreign key: for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "236",
            "5537",
            "6315",
            "386023",
            "79193",
            "480",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "8000.0000",
            "0.1500",
            "1200.00",
            "0.1500",
            "1200.00",
            "1200.00"
          ],
          "rowNumber": 1913339,
          "rowPosition": 1913340,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913340\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "73146",
            "1",
            "32",
            "100",
            "15856",
            "2174",
            "386023",
            "79192",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "3000.0000",
            "0.3200",
            "960.00",
            "0.3200",
            "960.00",
            "960.00"
          ],
          "rowNumber": 1913340,
          "rowPosition": 1913341,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913341\" violates the foreign key: for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "219",
            "6470",
            "139189",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "250.0000",
            "4.0000",
            "1000.00",
            "4.0000",
            "1000.00",
            "1000.00"
          ],
          "rowNumber": 1913341,
          "rowPosition": 1913342,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913342\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "19553",
            "36233",
            "386023",
            "79193",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "500.0000",
            "0.1100",
            "55.00",
            "0.1100",
            "55.00",
            "55.00"
          ],
          "rowNumber": 1913342,
          "rowPosition": 1913343,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913343\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "100",
            "6189",
            "136414",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "750.0000",
            "2.0000",
            "1500.00",
            "2.0000",
            "1500.00",
            "1500.00"
          ],
          "rowNumber": 1913343,
          "rowPosition": 1913344,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913344\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "6040",
            "34660",
            "386023",
            "79193",
            "480",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "2000.0000",
            "0.1500",
            "300.00",
            "0.1500",
            "300.00",
            "300.00"
          ],
          "rowNumber": 1913344,
          "rowPosition": 1913345,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913345\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "100",
            "14464",
            "86361",
            "386023",
            "79191",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "1000.0000",
            "16.3600",
            "16360.00",
            "16.3600",
            "16360.00",
            "16360.00"
          ],
          "rowNumber": 1913345,
          "rowPosition": 1913346,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913346\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "17320",
            "1",
            "32",
            "100",
            "14140",
            "35313",
            "386023",
            "79193",
            "480",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "10000.0000",
            "0.1300",
            "1300.00",
            "0.1300",
            "1300.00",
            "1300.00"
          ],
          "rowNumber": 1913346,
          "rowPosition": 1913347,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913347\" violates the foreign key: for \"id_contrato\": values \"79193\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "73146",
            "1",
            "32",
            "100",
            "10027",
            "117415",
            "386023",
            "79192",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "10.0000",
            "48.0000",
            "480.00",
            "48.0000",
            "480.00",
            "480.00"
          ],
          "rowNumber": 1913347,
          "rowPosition": 1913348,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913348\" violates the foreign key: for \"id_contrato\": values \"79192\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44469",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "71373",
            "1",
            "32",
            "327",
            "1321",
            "38312",
            "386023",
            "79191",
            "1215",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2023-01-06",
            "1.0000",
            "1000.0000",
            "1000.00",
            "1000.0000",
            "1000.00",
            "1000.00"
          ],
          "rowNumber": 1913348,
          "rowPosition": 1913349,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913349\" violates the foreign key: for \"id_contrato\": values \"79191\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44450",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "66",
            "19494",
            "1",
            "69",
            "439",
            "21705",
            "197096",
            "386041",
            "79194",
            "1927",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2023-01-09",
            "430.0000",
            "15.4600",
            "6647.80",
            "14.5000",
            "6235.00",
            "6235.00"
          ],
          "rowNumber": 1913391,
          "rowPosition": 1913392,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913392\" violates the foreign key: for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44450",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "19494",
            "1",
            "10",
            "428",
            "2681",
            "1466",
            "386041",
            "79194",
            "889",
            "1831307",
            "2586",
            "2082",
            "2022",
            "2023-01-09",
            "44.0000",
            "18.5400",
            "815.79",
            "18.5000",
            "814.00",
            "814.00"
          ],
          "rowNumber": 1913392,
          "rowPosition": 1913393,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913393\" violates the foreign key: for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44450",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "19494",
            "1",
            "69",
            "439",
            "21705",
            "197096",
            "386041",
            "79194",
            "1927",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2023-01-09",
            "1450.0000",
            "15.4600",
            "22417.00",
            "14.5000",
            "21025.00",
            "21025.00"
          ],
          "rowNumber": 1913393,
          "rowPosition": 1913394,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913394\" violates the foreign key: for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44450",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "430",
            "19494",
            "1",
            "69",
            "439",
            "21705",
            "197096",
            "386041",
            "79194",
            "1927",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2023-01-09",
            "560.0000",
            "15.4600",
            "8657.60",
            "14.5000",
            "8120.00",
            "8120.00"
          ],
          "rowNumber": 1913394,
          "rowPosition": 1913395,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913395\" violates the foreign key: for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44450",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "19494",
            "1",
            "69",
            "439",
            "21705",
            "197096",
            "386041",
            "79194",
            "1927",
            "1831312",
            "2538",
            "2082",
            "2022",
            "2023-01-09",
            "560.0000",
            "15.4600",
            "8657.60",
            "14.5000",
            "8120.00",
            "8120.00"
          ],
          "rowNumber": 1913395,
          "rowPosition": 1913396,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1913396\" violates the foreign key: for \"id_contrato\": values \"79194\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "856",
            "61702",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "385346",
            "79197",
            "889",
            "1831449",
            "2594",
            "2270",
            "2022",
            "2022-12-27",
            "0.0000",
            "3941741.2600",
            "3941741.26",
            "3181545.0000",
            "3181545.00",
            "3181545.00"
          ],
          "rowNumber": 1915258,
          "rowPosition": 1915259,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915259\" violates the foreign key: for \"id_contrato\": values \"79197\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44426",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "856",
            "72671",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "385346",
            "79195",
            "889",
            "1831449",
            "2594",
            "2270",
            "2022",
            "2022-12-27",
            "0.0000",
            "821319.2200",
            "821319.22",
            "734013.6400",
            "734013.64",
            "734013.64"
          ],
          "rowNumber": 1915263,
          "rowPosition": 1915264,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79195\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1915264\" violates the foreign key: for \"id_contrato\": values \"79195\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43523",
            "14",
            "1831030",
            "27",
            "1",
            "1",
            "66",
            "59686",
            "1",
            "51",
            "274",
            "4357",
            "92933",
            "385436",
            "79196",
            "889",
            "1831357",
            "2670",
            "2270",
            "2022",
            "2022-12-28",
            "0.0000",
            "1652.3500",
            "1652.35",
            "1260.0000",
            "1260.00",
            "1260.00"
          ],
          "rowNumber": 1916091,
          "rowPosition": 1916092,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916092\" violates the foreign key: for \"id_contrato\": values \"79196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44429",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "18979",
            "1",
            "32",
            "100",
            "10787",
            "132044",
            "385996",
            "79190",
            "480",
            "1831400",
            "2796",
            "2082",
            "2022",
            "2023-01-04",
            "600.0000",
            "72.4200",
            "43452.00",
            "60.0000",
            "36000.00",
            "36000.00"
          ],
          "rowNumber": 1916468,
          "rowPosition": 1916469,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916469\" violates the foreign key: for \"id_contrato\": values \"79190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44429",
            "4",
            "1831016",
            "16",
            "1",
            "1",
            "206",
            "18979",
            "1",
            "32",
            "100",
            "10787",
            "83628",
            "385996",
            "79190",
            "480",
            "1831400",
            "2796",
            "2082",
            "2022",
            "2023-01-04",
            "600.0000",
            "23.4300",
            "14058.00",
            "23.4300",
            "14058.00",
            "14058.00"
          ],
          "rowNumber": 1916469,
          "rowPosition": 1916470,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916470\" violates the foreign key: for \"id_contrato\": values \"79190\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "4",
            "1831084",
            "81",
            "1",
            "1",
            "66",
            "21005",
            "1",
            "39",
            "283",
            "21770",
            "193591",
            "386098",
            "79198",
            "889",
            "1831736",
            "3067",
            "1859",
            "2022",
            "2023-01-13",
            "0.0000",
            "13831.2000",
            "13831.20",
            "4610.4000",
            "4610.40",
            "4610.40"
          ],
          "rowNumber": 1916491,
          "rowPosition": 1916492,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916492\" violates the foreign key: for \"id_contrato\": values \"79198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "4",
            "1831084",
            "81",
            "1",
            "1",
            "66",
            "21005",
            "1",
            "39",
            "283",
            "21770",
            "193670",
            "386098",
            "79198",
            "889",
            "1831736",
            "3067",
            "1859",
            "2022",
            "2023-01-13",
            "0.0000",
            "36676.8000",
            "36676.80",
            "8252.3800",
            "8252.38",
            "8252.38"
          ],
          "rowNumber": 1916492,
          "rowPosition": 1916493,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916493\" violates the foreign key: for \"id_contrato\": values \"79198\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43523",
            "14",
            "1831030",
            "27",
            "1",
            "1",
            "66",
            "59686",
            "1",
            "51",
            "274",
            "4357",
            "92933",
            "385436",
            "79196",
            "889",
            "1831357",
            "2670",
            "2270",
            "2022",
            "2022-12-28",
            "0.0000",
            "567.0300",
            "567.03",
            "462.0000",
            "462.00",
            "462.00"
          ],
          "rowNumber": 1916616,
          "rowPosition": 1916617,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916617\" violates the foreign key: for \"id_contrato\": values \"79196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43523",
            "14",
            "1831030",
            "27",
            "1",
            "1",
            "66",
            "59686",
            "1",
            "51",
            "274",
            "4357",
            "92933",
            "385436",
            "79196",
            "889",
            "1831357",
            "2670",
            "2270",
            "2022",
            "2022-12-28",
            "0.0000",
            "2390.6200",
            "2390.61",
            "1848.0000",
            "1848.00",
            "1848.00"
          ],
          "rowNumber": 1916824,
          "rowPosition": 1916825,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"79196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1916825\" violates the foreign key: for \"id_contrato\": values \"79196\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 36
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 36,
    "tasks": 1
  },
  "valid": false
}