{
  "version": "4.38.0",
  "time": 401.197,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "dc6d6fd03c178493df2d470e75d26bd1",
          "bytes": 57727312,
          "fields": 27,
          "rows": 1892849
        }
      },
      "time": 401.197,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43584",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19898",
            "1",
            "42",
            "399",
            "13142",
            "229884",
            "380270",
            "77731",
            "889",
            "1831230",
            "2923",
            "3043",
            "2022",
            "2022-10-19",
            "120.0000",
            "877.0000",
            "105240.00",
            "877.0000",
            "105240.00",
            "105240.00"
          ],
          "rowNumber": 1818546,
          "rowPosition": 1818547,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77731\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818547\" violates the foreign key: for \"id_contrato\": values \"77731\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19898",
            "1",
            "42",
            "399",
            "11004",
            "229892",
            "380270",
            "77731",
            "889",
            "1831230",
            "2923",
            "3043",
            "2022",
            "2022-10-19",
            "10.0000",
            "1298.0000",
            "12980.00",
            "1298.0000",
            "12980.00",
            "12980.00"
          ],
          "rowNumber": 1818547,
          "rowPosition": 1818548,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77731\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818548\" violates the foreign key: for \"id_contrato\": values \"77731\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43584",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "19898",
            "1",
            "42",
            "399",
            "13142",
            "229876",
            "380270",
            "77731",
            "889",
            "1831230",
            "2923",
            "3043",
            "2022",
            "2022-10-19",
            "200.0000",
            "298.0000",
            "59600.00",
            "298.0000",
            "59600.00",
            "59600.00"
          ],
          "rowNumber": 1818548,
          "rowPosition": 1818549,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77731\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818549\" violates the foreign key: for \"id_contrato\": values \"77731\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43477",
            "13",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "20977",
            "1",
            "17",
            "379",
            "7051",
            "94368",
            "380122",
            "77727",
            "889",
            "1831370",
            "2816",
            "2633",
            "2022",
            "2022-10-17",
            "0.0000",
            "2043080.6800",
            "2043080.68",
            "2043080.6800",
            "2043080.68",
            "2043080.68"
          ],
          "rowNumber": 1819885,
          "rowPosition": 1819886,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77727\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1819886\" violates the foreign key: for \"id_contrato\": values \"77727\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157755",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "900.0000",
            "900.00",
            "870.0000",
            "870.00",
            "870.00"
          ],
          "rowNumber": 1824149,
          "rowPosition": 1824150,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1824150\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "1",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "9347",
            "1",
            "32",
            "327",
            "15327",
            "126875",
            "380147",
            "77739",
            "98",
            "1831400",
            "2925",
            "3331",
            "2022",
            "2022-10-17",
            "560.0000",
            "5376.2000",
            "3010672.00",
            "5376.2000",
            "3010672.00",
            "3010672.00"
          ],
          "rowNumber": 1825607,
          "rowPosition": 1825608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77739\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825608\" violates the foreign key: for \"id_contrato\": values \"77739\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "71763",
            "1",
            "42",
            "399",
            "6204",
            "47257",
            "378856",
            "77743",
            "889",
            "1831221",
            "2923",
            "2925",
            "2022",
            "2022-10-04",
            "40.0000",
            "50.0000",
            "2000.00",
            "50.0000",
            "2000.00",
            "2000.00"
          ],
          "rowNumber": 1844564,
          "rowPosition": 1844565,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1844565\" violates the foreign key: for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "71763",
            "1",
            "42",
            "399",
            "6204",
            "47257",
            "378856",
            "77743",
            "889",
            "1831221",
            "2923",
            "2925",
            "2022",
            "2022-10-04",
            "40.0000",
            "50.0000",
            "2000.00",
            "50.0000",
            "2000.00",
            "2000.00"
          ],
          "rowNumber": 1844592,
          "rowPosition": 1844593,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1844593\" violates the foreign key: for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831044",
            "36",
            "1",
            "1",
            "79",
            "71651",
            "1",
            "30",
            "173",
            "4355",
            "265907",
            "380423",
            "77741",
            "889",
            "1831355",
            "2670",
            "2633",
            "2022",
            "2022-10-20",
            "0.0000",
            "24998.8000",
            "24998.80",
            "21000.0000",
            "21000.00",
            "21000.00"
          ],
          "rowNumber": 1846931,
          "rowPosition": 1846932,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77741\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1846932\" violates the foreign key: for \"id_contrato\": values \"77741\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43565",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "66",
            "68732",
            "5",
            "77",
            "480",
            "22057",
            "217883",
            "380391",
            "77738",
            "1729",
            "1831531",
            "2738",
            "2270",
            "2022",
            "2022-10-20",
            "0.0000",
            "9019.6800",
            "9019.68",
            "9019.6800",
            "9019.68",
            "9019.68"
          ],
          "rowNumber": 1850792,
          "rowPosition": 1850793,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77738\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850793\" violates the foreign key: for \"id_contrato\": values \"77738\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43492",
            "5",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "22801",
            "1",
            "17",
            "379",
            "7051",
            "94368",
            "380937",
            "77733",
            "889",
            "1831370",
            "2816",
            "2633",
            "2022",
            "2022-10-27",
            "0.0000",
            "3658521.6200",
            "3658521.62",
            "3124749.2500",
            "3124749.25",
            "3124749.25"
          ],
          "rowNumber": 1851787,
          "rowPosition": 1851788,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77733\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1851788\" violates the foreign key: for \"id_contrato\": values \"77733\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "13366",
            "249033",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "9990.0000",
            "9990.00",
            "8572.0000",
            "8572.00",
            "8572.00"
          ],
          "rowNumber": 1869025,
          "rowPosition": 1869026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869026\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "13366",
            "188241",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "9990.0000",
            "9990.00",
            "8690.0000",
            "8690.00",
            "8690.00"
          ],
          "rowNumber": 1869026,
          "rowPosition": 1869027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869027\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "8353",
            "197448",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "8890.0000",
            "8890.00",
            "8450.0000",
            "8450.00",
            "8450.00"
          ],
          "rowNumber": 1869027,
          "rowPosition": 1869028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869028\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "4026",
            "150976",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "18890.0000",
            "18890.00",
            "11190.0000",
            "11190.00",
            "11190.00"
          ],
          "rowNumber": 1869028,
          "rowPosition": 1869029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869029\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "22429",
            "282245",
            "379709",
            "77745",
            "1729",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "7990.0000",
            "7990.00",
            "2650.0000",
            "2650.00",
            "2650.00"
          ],
          "rowNumber": 1869029,
          "rowPosition": 1869030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869030\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "13366",
            "174221",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "7990.0000",
            "7990.00",
            "8430.0000",
            "8430.00",
            "8430.00"
          ],
          "rowNumber": 1869030,
          "rowPosition": 1869031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869031\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "13366",
            "133942",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "1.0000",
            "9990.0000",
            "9990.00",
            "8450.0000",
            "8450.00",
            "8450.00"
          ],
          "rowNumber": 1869031,
          "rowPosition": 1869032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869032\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "14074",
            "127446",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "6.0000",
            "60.0000",
            "360.00",
            "100.0000",
            "600.00",
            "600.00"
          ],
          "rowNumber": 1869032,
          "rowPosition": 1869033,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869033\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "14074",
            "58450",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "18.0000",
            "115.0000",
            "2070.00",
            "200.0000",
            "3600.00",
            "3600.00"
          ],
          "rowNumber": 1869033,
          "rowPosition": 1869034,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869034\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "14074",
            "30992",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "6.0000",
            "180.0000",
            "1080.00",
            "300.0000",
            "1800.00",
            "1800.00"
          ],
          "rowNumber": 1869034,
          "rowPosition": 1869035,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869035\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "615",
            "23318",
            "1",
            "56",
            "527",
            "14074",
            "30993",
            "379709",
            "77745",
            "889",
            "1831940",
            "2814",
            "3043",
            "2022",
            "2022-10-11",
            "10.0000",
            "260.0000",
            "2600.00",
            "400.0000",
            "4000.00",
            "4000.00"
          ],
          "rowNumber": 1869035,
          "rowPosition": 1869036,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869036\" violates the foreign key: for \"id_contrato\": values \"77745\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43543",
            "4",
            "1831027",
            "22",
            "1",
            "1",
            "66",
            "35003",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "380223",
            "77735",
            "889",
            "1831731",
            "2954",
            "2045",
            "2022",
            "2022-10-18",
            "0.0000",
            "167553.5800",
            "167553.58",
            "138000.0000",
            "138000.00",
            "138000.00"
          ],
          "rowNumber": 1869337,
          "rowPosition": 1869338,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77735\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869338\" violates the foreign key: for \"id_contrato\": values \"77735\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43544",
            "2",
            "1831105",
            "91",
            "1",
            "1",
            "338",
            "72510",
            "1",
            "9",
            "581",
            "12418",
            "93129",
            "380491",
            "77740",
            "322",
            "1831697",
            "2932",
            "3042",
            "2022",
            "2022-10-21",
            "0.0000",
            "18000.0000",
            "18000.00",
            "18000.0000",
            "18000.00",
            "18000.00"
          ],
          "rowNumber": 1869350,
          "rowPosition": 1869351,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77740\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1869351\" violates the foreign key: for \"id_contrato\": values \"77740\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "15",
            "1831100",
            "99",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "16006",
            "118342",
            "379454",
            "77729",
            "190",
            "1831313",
            "2928",
            "3331",
            "2022",
            "2022-10-07",
            "15000.0000",
            "5.9700",
            "89529.00",
            "5.9700",
            "89529.00",
            "89529.00"
          ],
          "rowNumber": 1871978,
          "rowPosition": 1871979,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77729\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1871979\" violates the foreign key: for \"id_contrato\": values \"77729\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "15",
            "1831100",
            "99",
            "1",
            "1",
            "883",
            "379",
            "1",
            "57",
            "779",
            "2941",
            "5465",
            "379454",
            "77729",
            "190",
            "1831313",
            "2928",
            "3331",
            "2022",
            "2022-10-07",
            "10000.0000",
            "4.1100",
            "41082.00",
            "4.1100",
            "41082.00",
            "41082.00"
          ],
          "rowNumber": 1871979,
          "rowPosition": 1871980,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77729\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1871980\" violates the foreign key: for \"id_contrato\": values \"77729\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43512",
            "4",
            "1831030",
            "27",
            "1",
            "1",
            "248",
            "4076",
            "1",
            "77",
            "479",
            "4462",
            "163288",
            "378897",
            "77744",
            "889",
            "1831808",
            "2548",
            "2270",
            "2022",
            "2022-10-07",
            "0.0000",
            "581760.0000",
            "581760.00",
            "131220.0000",
            "131220.00",
            "131220.00"
          ],
          "rowNumber": 1872847,
          "rowPosition": 1872848,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77744\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1872848\" violates the foreign key: for \"id_contrato\": values \"77744\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831013",
            "8",
            "1",
            "1",
            "883",
            "19695",
            "1",
            "39",
            "712",
            "20379",
            "265551",
            "380233",
            "77746",
            "889",
            "1831925",
            "3067",
            "2820",
            "2022",
            "2022-10-18",
            "0.0000",
            "60.0000",
            "60.00",
            "60.0000",
            "60.00",
            "60.00"
          ],
          "rowNumber": 1880071,
          "rowPosition": 1880072,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880072\" violates the foreign key: for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831013",
            "8",
            "1",
            "1",
            "883",
            "19695",
            "1",
            "39",
            "712",
            "7131",
            "265542",
            "380233",
            "77746",
            "889",
            "1831925",
            "3067",
            "2820",
            "2022",
            "2022-10-18",
            "0.0000",
            "60.0000",
            "60.00",
            "60.0000",
            "60.00",
            "60.00"
          ],
          "rowNumber": 1880072,
          "rowPosition": 1880073,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880073\" violates the foreign key: for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831013",
            "8",
            "1",
            "1",
            "883",
            "19695",
            "1",
            "39",
            "712",
            "7131",
            "161473",
            "380233",
            "77746",
            "889",
            "1831925",
            "3067",
            "2820",
            "2022",
            "2022-10-18",
            "0.0000",
            "329.0000",
            "329.00",
            "329.0000",
            "329.00",
            "329.00"
          ],
          "rowNumber": 1880073,
          "rowPosition": 1880074,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880074\" violates the foreign key: for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831013",
            "8",
            "1",
            "1",
            "883",
            "19695",
            "1",
            "39",
            "712",
            "20379",
            "161459",
            "380233",
            "77746",
            "889",
            "1831925",
            "3067",
            "2820",
            "2022",
            "2022-10-18",
            "0.0000",
            "75.0000",
            "75.00",
            "75.0000",
            "75.00",
            "75.00"
          ],
          "rowNumber": 1880074,
          "rowPosition": 1880075,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880075\" violates the foreign key: for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831013",
            "8",
            "1",
            "1",
            "883",
            "19695",
            "1",
            "39",
            "712",
            "7131",
            "171415",
            "380233",
            "77746",
            "889",
            "1831925",
            "3067",
            "2820",
            "2022",
            "2022-10-18",
            "0.0000",
            "140.0000",
            "140.00",
            "140.0000",
            "140.00",
            "140.00"
          ],
          "rowNumber": 1880075,
          "rowPosition": 1880076,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880076\" violates the foreign key: for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831013",
            "8",
            "1",
            "1",
            "883",
            "19695",
            "1",
            "39",
            "712",
            "20379",
            "161454",
            "380233",
            "77746",
            "889",
            "1831925",
            "3067",
            "2820",
            "2022",
            "2022-10-18",
            "0.0000",
            "144.0000",
            "144.00",
            "144.0000",
            "144.00",
            "144.00"
          ],
          "rowNumber": 1880076,
          "rowPosition": 1880077,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880077\" violates the foreign key: for \"id_contrato\": values \"77746\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "17",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "72350",
            "1",
            "46",
            "10",
            "316",
            "374936",
            "379342",
            "77747",
            "889",
            "1831846",
            "3078",
            "2046",
            "2022",
            "2022-10-06",
            "61.0000",
            "695.0000",
            "42395.00",
            "695.0000",
            "42395.00",
            "42395.00"
          ],
          "rowNumber": 1882030,
          "rowPosition": 1882031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77747\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1882031\" violates the foreign key: for \"id_contrato\": values \"77747\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43537",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "825",
            "56033",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "378701",
            "77728",
            "981",
            "1831731",
            "2879",
            "3043",
            "2022",
            "2022-09-27",
            "0.0000",
            "313607.5200",
            "313607.52",
            "291100.0000",
            "291100.00",
            "291100.00"
          ],
          "rowNumber": 1883864,
          "rowPosition": 1883865,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77728\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883865\" violates the foreign key: for \"id_contrato\": values \"77728\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43537",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "38",
            "61996",
            "1",
            "77",
            "700",
            "17682",
            "93674",
            "378701",
            "77737",
            "981",
            "1831731",
            "2879",
            "3043",
            "2022",
            "2022-09-27",
            "0.0000",
            "52267.9200",
            "52267.92",
            "52267.9200",
            "52267.92",
            "52267.92"
          ],
          "rowNumber": 1883865,
          "rowPosition": 1883866,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77737\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883866\" violates the foreign key: for \"id_contrato\": values \"77737\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "66",
            "67387",
            "1",
            "41",
            "806",
            "9790",
            "207006",
            "378669",
            "77732",
            "889",
            "1831435",
            "2594",
            "2631",
            "2022",
            "2022-09-27",
            "1.0000",
            "641.1800",
            "641.18",
            "641.1800",
            "641.18",
            "641.18"
          ],
          "rowNumber": 1883911,
          "rowPosition": 1883912,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883912\" violates the foreign key: for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "66",
            "67387",
            "1",
            "41",
            "806",
            "9790",
            "156136",
            "378669",
            "77732",
            "28",
            "1831435",
            "2594",
            "2631",
            "2022",
            "2022-09-27",
            "4.0000",
            "2775.0000",
            "11100.00",
            "2775.0000",
            "11100.00",
            "11100.00"
          ],
          "rowNumber": 1883912,
          "rowPosition": 1883913,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883913\" violates the foreign key: for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "66",
            "67387",
            "1",
            "41",
            "806",
            "9790",
            "171371",
            "378669",
            "77732",
            "889",
            "1831435",
            "2594",
            "2631",
            "2022",
            "2022-09-27",
            "1.0000",
            "5117.5000",
            "5117.50",
            "5117.5000",
            "5117.50",
            "5117.50"
          ],
          "rowNumber": 1883913,
          "rowPosition": 1883914,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883914\" violates the foreign key: for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "66",
            "67387",
            "1",
            "41",
            "806",
            "9790",
            "171345",
            "378669",
            "77732",
            "889",
            "1831435",
            "2594",
            "2631",
            "2022",
            "2022-09-27",
            "1.0000",
            "5275.0000",
            "5275.00",
            "5275.0000",
            "5275.00",
            "5275.00"
          ],
          "rowNumber": 1883914,
          "rowPosition": 1883915,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883915\" violates the foreign key: for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "15",
            "1831096",
            "92",
            "1",
            "1",
            "66",
            "67387",
            "1",
            "41",
            "806",
            "9790",
            "171372",
            "378669",
            "77732",
            "889",
            "1831435",
            "2594",
            "2631",
            "2022",
            "2022-09-27",
            "1.0000",
            "4921.3500",
            "4921.35",
            "4921.3500",
            "4921.35",
            "4921.35"
          ],
          "rowNumber": 1883915,
          "rowPosition": 1883916,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883916\" violates the foreign key: for \"id_contrato\": values \"77732\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43548",
            "1",
            "1831105",
            "91",
            "1",
            "1",
            "66",
            "20109",
            "1",
            "39",
            "834",
            "22816",
            "368184",
            "378885",
            "77730",
            "1729",
            "1831739",
            "3067",
            "3294",
            "2022",
            "2022-09-29",
            "0.0000",
            "1637255.5100",
            "1637255.51",
            "1637255.5100",
            "1637255.51",
            "1637255.51"
          ],
          "rowNumber": 1883937,
          "rowPosition": 1883938,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77730\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1883938\" violates the foreign key: for \"id_contrato\": values \"77730\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "71763",
            "1",
            "42",
            "399",
            "16145",
            "94301",
            "378856",
            "77743",
            "889",
            "1831334",
            "2923",
            "2925",
            "2022",
            "2022-09-29",
            "200.0000",
            "2.3500",
            "470.00",
            "2.3500",
            "470.00",
            "470.00"
          ],
          "rowNumber": 1887690,
          "rowPosition": 1887691,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887691\" violates the foreign key: for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43506",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "883",
            "71763",
            "1",
            "42",
            "399",
            "10152",
            "128966",
            "378856",
            "77743",
            "889",
            "1831334",
            "2923",
            "2925",
            "2022",
            "2022-09-29",
            "400.0000",
            "3.8000",
            "1520.00",
            "3.8000",
            "1520.00",
            "1520.00"
          ],
          "rowNumber": 1887696,
          "rowPosition": 1887697,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887697\" violates the foreign key: for \"id_contrato\": values \"77743\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43536",
            "15",
            "1831059",
            "57",
            "1",
            "1",
            "883",
            "33019",
            "1",
            "3",
            "627",
            "3013",
            "226208",
            "376842",
            "77736",
            "889",
            "1831295",
            "2611",
            "2081",
            "2022",
            "2022-09-02",
            "1.0000",
            "4921.1000",
            "4921.10",
            "4921.1000",
            "4921.10",
            "4921.10"
          ],
          "rowNumber": 1888291,
          "rowPosition": 1888292,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77736\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888292\" violates the foreign key: for \"id_contrato\": values \"77736\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "14415.0000",
            "619.84",
            "543.8600",
            "543.86",
            "543.86"
          ],
          "rowNumber": 1888410,
          "rowPosition": 1888411,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888411\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "14415.0000",
            "387.76",
            "340.2300",
            "340.23",
            "340.23"
          ],
          "rowNumber": 1888411,
          "rowPosition": 1888412,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888412\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "14415.0000",
            "3486.99",
            "3059.5500",
            "3059.55",
            "3059.55"
          ],
          "rowNumber": 1888412,
          "rowPosition": 1888413,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888413\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "14415.0000",
            "929.77",
            "815.8000",
            "815.80",
            "815.80"
          ],
          "rowNumber": 1889845,
          "rowPosition": 1889846,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1889846\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "14415.0000",
            "8680.72",
            "7616.6300",
            "7616.63",
            "7616.63"
          ],
          "rowNumber": 1889846,
          "rowPosition": 1889847,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1889847\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "14",
            "1831095",
            "96",
            "1",
            "1",
            "876",
            "62715",
            "1",
            "77",
            "533",
            "1804",
            "157757",
            "380334",
            "77734",
            "889",
            "1831586",
            "2738",
            "3293",
            "2022",
            "2022-10-19",
            "0.0000",
            "14415.0000",
            "309.92",
            "271.9300",
            "271.93",
            "271.93"
          ],
          "rowNumber": 1889847,
          "rowPosition": 1889848,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1889848\" violates the foreign key: for \"id_contrato\": values \"77734\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 51
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 51,
    "tasks": 1
  },
  "valid": false
}