{
  "version": "4.38.0",
  "time": 403.896,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "description": "- > \n  Chave estrangeira (Foreign Key) que aponta para a Chave Primária (Primary keys) da tabela dm_tempo_diario. \n  Ou seja, por meio dessa chave é possível identificar a data completa a qual o dado se refere.\n\n  Nota: \n  No site dados.mg.gov.br a tabela dm_tempo_diario pode ser encontrada no recurso Calendários - Dias \n  de cada conjunto.\n",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "fb6b52e9f534f5dbf03eb8d7e4f6d0d5",
          "bytes": 58109703,
          "fields": 27,
          "rows": 1906516
        }
      },
      "time": 403.896,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43571",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15185",
            "1",
            "32",
            "100",
            "2267",
            "127696",
            "380844",
            "78306",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-10-26",
            "20.0000",
            "26.7000",
            "534.00",
            "26.7000",
            "534.00",
            "534.00"
          ],
          "rowNumber": 1815458,
          "rowPosition": 1815459,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78306\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815459\" violates the foreign key: for \"id_contrato\": values \"78306\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "2",
            "1831100",
            "99",
            "1",
            "1",
            "66",
            "15185",
            "1",
            "32",
            "100",
            "9030",
            "74535",
            "380844",
            "78306",
            "1292",
            "1831400",
            "2796",
            "3331",
            "2022",
            "2022-10-26",
            "100.0000",
            "3.7900",
            "379.00",
            "3.7900",
            "379.00",
            "379.00"
          ],
          "rowNumber": 1815461,
          "rowPosition": 1815462,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78306\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1815462\" violates the foreign key: for \"id_contrato\": values \"78306\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "10551",
            "80536",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "38.0000",
            "1654.1700",
            "62858.46",
            "1654.1700",
            "62858.46",
            "62858.46"
          ],
          "rowNumber": 1816022,
          "rowPosition": 1816023,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816023\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "5974",
            "80209",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "38.0000",
            "259.4700",
            "9859.86",
            "259.4700",
            "9859.86",
            "9859.86"
          ],
          "rowNumber": 1816023,
          "rowPosition": 1816024,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816024\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "15872",
            "79201",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "13.0000",
            "1297.4100",
            "16866.33",
            "1297.4100",
            "16866.33",
            "16866.33"
          ],
          "rowNumber": 1816024,
          "rowPosition": 1816025,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816025\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "10631",
            "80156",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "20.0000",
            "3902.6700",
            "78053.40",
            "3902.6700",
            "78053.40",
            "78053.40"
          ],
          "rowNumber": 1816025,
          "rowPosition": 1816026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816026\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "10551",
            "100668",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "11.0000",
            "1238.8000",
            "13626.80",
            "1238.8000",
            "13626.80",
            "13626.80"
          ],
          "rowNumber": 1816026,
          "rowPosition": 1816027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816027\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "66",
            "79068",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "18.0000",
            "1515.7300",
            "27283.14",
            "1515.7300",
            "27283.14",
            "27283.14"
          ],
          "rowNumber": 1816027,
          "rowPosition": 1816028,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816028\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "3149",
            "19489",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "16.0000",
            "569.5300",
            "9112.48",
            "569.5300",
            "9112.48",
            "9112.48"
          ],
          "rowNumber": 1816028,
          "rowPosition": 1816029,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816029\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "19",
            "628",
            "5308",
            "90138",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "40.0000",
            "2204.2500",
            "88170.00",
            "2204.2500",
            "88170.00",
            "88170.00"
          ],
          "rowNumber": 1816029,
          "rowPosition": 1816030,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816030\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "15872",
            "79113",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "2.0000",
            "1345.3500",
            "2690.70",
            "1345.3500",
            "2690.70",
            "2690.70"
          ],
          "rowNumber": 1816030,
          "rowPosition": 1816031,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816031\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43564",
            "1",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "20687",
            "1",
            "42",
            "107",
            "2716",
            "162726",
            "382982",
            "78299",
            "889",
            "1831334",
            "2995",
            "3043",
            "2022",
            "2022-11-28",
            "5.0000",
            "2500.0000",
            "12500.00",
            "2500.0000",
            "12500.00",
            "12500.00"
          ],
          "rowNumber": 1816031,
          "rowPosition": 1816032,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816032\" violates the foreign key: for \"id_contrato\": values \"78299\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43537",
            "13",
            "1831009",
            "1",
            "1",
            "1",
            "662",
            "60232",
            "1",
            "17",
            "185",
            "20222",
            "92554",
            "383068",
            "78307",
            "889",
            "1831370",
            "2816",
            "2413",
            "2022",
            "2022-11-29",
            "0.0000",
            "199976.8100",
            "199976.81",
            "198085.7300",
            "198085.73",
            "198085.73"
          ],
          "rowNumber": 1818889,
          "rowPosition": 1818890,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78307\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818890\" violates the foreign key: for \"id_contrato\": values \"78307\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44399",
            "1",
            "1831016",
            "16",
            "1",
            "1",
            "430",
            "22000",
            "1",
            "77",
            "73",
            "9726",
            "92493",
            "381242",
            "78294",
            "889",
            "1831901",
            "2623",
            "2082",
            "2022",
            "2022-11-04",
            "0.0000",
            "224902.0000",
            "224902.00",
            "224902.0000",
            "224902.00",
            "224902.00"
          ],
          "rowNumber": 1820215,
          "rowPosition": 1820216,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78294\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1820216\" violates the foreign key: for \"id_contrato\": values \"78294\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43523",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "334",
            "71927",
            "1",
            "17",
            "379",
            "9824",
            "94353",
            "383340",
            "78296",
            "889",
            "1831370",
            "2594",
            "2083",
            "2022",
            "2022-12-01",
            "0.0000",
            "22115.0600",
            "22115.06",
            "22115.0600",
            "22115.06",
            "22115.06"
          ],
          "rowNumber": 1850461,
          "rowPosition": 1850462,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78296\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850462\" violates the foreign key: for \"id_contrato\": values \"78296\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43523",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "497",
            "71927",
            "1",
            "17",
            "379",
            "9824",
            "94353",
            "383340",
            "78309",
            "889",
            "1831370",
            "2594",
            "2083",
            "2022",
            "2022-12-01",
            "0.0000",
            "84140.9900",
            "84140.99",
            "84140.9900",
            "84140.99",
            "84140.99"
          ],
          "rowNumber": 1850462,
          "rowPosition": 1850463,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78309\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850463\" violates the foreign key: for \"id_contrato\": values \"78309\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43523",
            "4",
            "1831083",
            "82",
            "1",
            "1",
            "213",
            "71927",
            "1",
            "17",
            "379",
            "9824",
            "94353",
            "383340",
            "78308",
            "889",
            "1831370",
            "2594",
            "2083",
            "2022",
            "2022-12-01",
            "0.0000",
            "21419.7000",
            "21419.70",
            "21419.7000",
            "21419.70",
            "21419.70"
          ],
          "rowNumber": 1850463,
          "rowPosition": 1850464,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78308\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1850464\" violates the foreign key: for \"id_contrato\": values \"78308\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43556",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "857",
            "6845",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "382922",
            "78301",
            "1968",
            "1831449",
            "2594",
            "1760",
            "2022",
            "2022-11-25",
            "0.0000",
            "6223074.0600",
            "6223074.06",
            "5938998.8200",
            "5938998.82",
            "5938998.82"
          ],
          "rowNumber": 1852549,
          "rowPosition": 1852550,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78301\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852550\" violates the foreign key: for \"id_contrato\": values \"78301\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44438",
            "14",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "27921",
            "1",
            "77",
            "533",
            "14815",
            "91062",
            "383200",
            "78295",
            "889",
            "1831754",
            "2738",
            "3043",
            "2022",
            "2022-11-30",
            "0.0000",
            "2500.0000",
            "2500.00",
            "2476.0000",
            "2476.00",
            "2476.00"
          ],
          "rowNumber": 1852579,
          "rowPosition": 1852580,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78295\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1852580\" violates the foreign key: for \"id_contrato\": values \"78295\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44413",
            "17",
            "1831044",
            "36",
            "1",
            "1",
            "883",
            "24687",
            "1",
            "17",
            "379",
            "17564",
            "246594",
            "381556",
            "78311",
            "1968",
            "1831370",
            "2594",
            "2633",
            "2022",
            "2022-11-09",
            "0.0000",
            "37470787.2000",
            "37470787.20",
            "37470787.2000",
            "37470787.20",
            "37470787.20"
          ],
          "rowNumber": 1855151,
          "rowPosition": 1855152,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78311\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1855152\" violates the foreign key: for \"id_contrato\": values \"78311\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43530",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "71133",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "383260",
            "78312",
            "889",
            "1831744",
            "2937",
            "2925",
            "2022",
            "2022-12-01",
            "0.0000",
            "10155.6000",
            "10155.60",
            "9847.3200",
            "9847.32",
            "9847.32"
          ],
          "rowNumber": 1857810,
          "rowPosition": 1857811,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78312\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857811\" violates the foreign key: for \"id_contrato\": values \"78312\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43530",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "71133",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "383260",
            "78312",
            "889",
            "1831744",
            "2937",
            "2925",
            "2022",
            "2022-12-01",
            "0.0000",
            "28875.6000",
            "28875.60",
            "3463.3200",
            "3463.32",
            "3463.32"
          ],
          "rowNumber": 1857845,
          "rowPosition": 1857846,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78312\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1857846\" violates the foreign key: for \"id_contrato\": values \"78312\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44439",
            "15",
            "1831044",
            "36",
            "1",
            "1",
            "66",
            "64949",
            "1",
            "9",
            "576",
            "14933",
            "166668",
            "383180",
            "78303",
            "889",
            "1831681",
            "2736",
            "2633",
            "2022",
            "2022-11-30",
            "120.0000",
            "320.0000",
            "38400.00",
            "320.0000",
            "38400.00",
            "38400.00"
          ],
          "rowNumber": 1858009,
          "rowPosition": 1858010,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78303\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858010\" violates the foreign key: for \"id_contrato\": values \"78303\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43530",
            "4",
            "1831008",
            "5",
            "1",
            "1",
            "66",
            "71133",
            "1",
            "77",
            "271",
            "1817",
            "93794",
            "383260",
            "78312",
            "889",
            "1831744",
            "2937",
            "2925",
            "2022",
            "2022-12-01",
            "0.0000",
            "155968.8000",
            "155968.80",
            "53189.3600",
            "53189.36",
            "53189.36"
          ],
          "rowNumber": 1858710,
          "rowPosition": 1858711,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78312\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858711\" violates the foreign key: for \"id_contrato\": values \"78312\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "17",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "65849",
            "1",
            "29",
            "785",
            "20877",
            "155175",
            "382907",
            "78297",
            "889",
            "1831975",
            "2927",
            "3043",
            "2022",
            "2022-11-25",
            "12.0000",
            "1342.0000",
            "16104.00",
            "1342.0000",
            "16104.00",
            "16104.00"
          ],
          "rowNumber": 1858818,
          "rowPosition": 1858819,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78297\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858819\" violates the foreign key: for \"id_contrato\": values \"78297\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44434",
            "17",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "28773",
            "1",
            "29",
            "785",
            "14916",
            "304270",
            "382907",
            "78310",
            "889",
            "1831975",
            "2927",
            "3043",
            "2022",
            "2022-11-25",
            "180.0000",
            "228.8100",
            "41185.80",
            "228.8100",
            "41185.80",
            "41185.80"
          ],
          "rowNumber": 1858819,
          "rowPosition": 1858820,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78310\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1858820\" violates the foreign key: for \"id_contrato\": values \"78310\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44432",
            "15",
            "1831099",
            "90",
            "1",
            "1",
            "66",
            "4625",
            "1",
            "54",
            "502",
            "6435",
            "317521",
            "383430",
            "78305",
            "889",
            "1831296",
            "2944",
            "2001",
            "2022",
            "2022-12-02",
            "24.0000",
            "1499.0000",
            "35976.00",
            "1499.0000",
            "35976.00",
            "35976.00"
          ],
          "rowNumber": 1861383,
          "rowPosition": 1861384,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78305\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1861384\" violates the foreign key: for \"id_contrato\": values \"78305\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43585",
            "14",
            "1831105",
            "91",
            "1",
            "1",
            "76",
            "72474",
            "1",
            "77",
            "188",
            "12311",
            "91631",
            "380567",
            "78298",
            "889",
            "1831769",
            "2590",
            "3042",
            "2022",
            "2022-10-21",
            "0.0000",
            "1400.0000",
            "1400.00",
            "1400.0000",
            "1400.00",
            "1400.00"
          ],
          "rowNumber": 1878806,
          "rowPosition": 1878807,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78298\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1878807\" violates the foreign key: for \"id_contrato\": values \"78298\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "1",
            "1831016",
            "16",
            "1",
            "1",
            "315",
            "22000",
            "1",
            "77",
            "73",
            "9726",
            "92493",
            "378716",
            "78304",
            "889",
            "1831901",
            "2623",
            "2082",
            "2022",
            "2022-09-27",
            "0.0000",
            "259468.9400",
            "259468.94",
            "259468.9400",
            "259468.94",
            "259468.94"
          ],
          "rowNumber": 1894597,
          "rowPosition": 1894598,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78304\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894598\" violates the foreign key: for \"id_contrato\": values \"78304\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "17536",
            "1",
            "48",
            "117",
            "19461",
            "223937",
            "381703",
            "78300",
            "889",
            "1831329",
            "3075",
            "3043",
            "2022",
            "2022-11-10",
            "31.0000",
            "94.5000",
            "2929.50",
            "94.5000",
            "2929.50",
            "2929.50"
          ],
          "rowNumber": 1894657,
          "rowPosition": 1894658,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78300\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1894658\" violates the foreign key: for \"id_contrato\": values \"78300\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43554",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "67674",
            "1",
            "17",
            "379",
            "17564",
            "94354",
            "382213",
            "78302",
            "889",
            "1831449",
            "2594",
            "3955",
            "2022",
            "2022-11-18",
            "0.0000",
            "119533.6000",
            "119533.60",
            "96555.7700",
            "96555.77",
            "96555.77"
          ],
          "rowNumber": 1904055,
          "rowPosition": 1904056,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"78302\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1904056\" violates the foreign key: for \"id_contrato\": values \"78302\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 31
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 31,
    "tasks": 1
  },
  "valid": false
}