{
  "version": "4.38.0",
  "time": 402.122,
  "errors": [],
  "tasks": [
    {
      "resource": {
        "name": "ft_compras",
        "title": "Compras",
        "path": "data/ft_compras.csv.gz",
        "schema": {
          "fields": [
            {
              "name": "id_tempo",
              "title": "Tempo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_procedimento",
              "title": "Procedimento de Contratação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_demanda",
              "title": "Órgão Demandante - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_orgao_contrato",
              "title": "Órgão do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_proc",
              "title": "Situação do Processo de Compra - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_situacao_cont",
              "title": "Situação do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_municipio",
              "title": "Município - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contratado",
              "title": "Contratado - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_tipo_licitacao",
              "title": "Tipo de Licitação - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_grupo_matserv",
              "title": "Grupo Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_classe_matserv",
              "title": "Classe Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_material_servico",
              "title": "Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item_matserv",
              "title": "Item Material e Serviço - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_processo",
              "title": "Processo - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_contrato",
              "title": "Número do Contrato - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_medida",
              "title": "Unidade de Medida - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_linha_fornec",
              "title": "Linha de Fornecimento - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_item",
              "title": "Item - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true,
                "unique": false
              }
            },
            {
              "name": "id_unidade_orc",
              "title": "Unidade Orçamentária - Chave",
              "type": "integer",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "unique": false
              }
            },
            {
              "name": "ano_particao",
              "title": "Ano Partição",
              "type": "year",
              "format": "default",
              "bareNumber": true,
              "constraints": {
                "required": true
              }
            },
            {
              "name": "dt_item_homologa",
              "title": "Data da Homologação do Item",
              "type": "date",
              "format": "default",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "qt_item_pedido",
              "title": "Item do Pedido - Quantidade",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_referencia",
              "title": "Valor Unitário de Referência",
              "description": "Valor unitário estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_referencia",
              "title": "Valor de Referência",
              "description": "Valor estimado de um determinado bem ou serviço, obtido por meio de pesquisa de mercado ou cadastro de preços.\n",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_un_homologado",
              "title": "Valor Unitário Homologado",
              "description": "Valor unitário final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_homologado",
              "title": "Valor Homologado",
              "description": "Valor final licitado ou comprado.",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            },
            {
              "name": "vr_atualizado",
              "title": "Valor Atualizado",
              "type": "number",
              "format": "default",
              "bareNumber": true,
              "decimalChar": ".",
              "constraints": {
                "required": true
              }
            }
          ],
          "missingValues": [
            ""
          ],
          "foreignKeys": [
            {
              "fields": [
                "id_processo"
              ],
              "reference": {
                "fields": [
                  "id_processo"
                ],
                "resource": "dm_processo"
              }
            },
            {
              "fields": [
                "id_situacao_cont"
              ],
              "reference": {
                "fields": [
                  "id_situacao_cont"
                ],
                "resource": "dm_situacao_cont"
              }
            },
            {
              "fields": [
                "id_situacao_proc"
              ],
              "reference": {
                "fields": [
                  "id_situacao_proc"
                ],
                "resource": "dm_situacao_proc"
              }
            },
            {
              "fields": [
                "id_linha_fornec"
              ],
              "reference": {
                "fields": [
                  "id_linha_fornec"
                ],
                "resource": "dm_linha_fornec"
              }
            },
            {
              "fields": [
                "id_classe_matserv"
              ],
              "reference": {
                "fields": [
                  "id_classe_matserv"
                ],
                "resource": "dm_classe_matserv"
              }
            },
            {
              "fields": [
                "id_tempo"
              ],
              "reference": {
                "fields": [
                  "id_tempo"
                ],
                "resource": "dm_tempo_diario"
              }
            },
            {
              "fields": [
                "id_municipio"
              ],
              "reference": {
                "fields": [
                  "id_municipio"
                ],
                "resource": "dm_municipio"
              }
            },
            {
              "fields": [
                "id_item_matserv"
              ],
              "reference": {
                "fields": [
                  "id_item_matserv"
                ],
                "resource": "dm_item_matserv"
              }
            },
            {
              "fields": [
                "id_tipo_licitacao"
              ],
              "reference": {
                "fields": [
                  "id_tipo_licitacao"
                ],
                "resource": "dm_tipo_licitacao"
              }
            },
            {
              "fields": [
                "id_item"
              ],
              "reference": {
                "fields": [
                  "id_item"
                ],
                "resource": "dm_item_desp"
              }
            },
            {
              "fields": [
                "id_material_servico"
              ],
              "reference": {
                "fields": [
                  "id_material_servico"
                ],
                "resource": "dm_material_servico"
              }
            },
            {
              "fields": [
                "id_orgao_contrato"
              ],
              "reference": {
                "fields": [
                  "id_orgao_contrato"
                ],
                "resource": "dm_orgao_contrato"
              }
            },
            {
              "fields": [
                "id_contrato"
              ],
              "reference": {
                "fields": [
                  "id_contrato"
                ],
                "resource": "dm_contrato"
              }
            },
            {
              "fields": [
                "id_orgao_demanda"
              ],
              "reference": {
                "fields": [
                  "id_orgao_demanda"
                ],
                "resource": "dm_orgao_demanda"
              }
            },
            {
              "fields": [
                "id_unidade_medida"
              ],
              "reference": {
                "fields": [
                  "id_unidade_medida"
                ],
                "resource": "dm_unidade_medida"
              }
            },
            {
              "fields": [
                "id_grupo_matserv"
              ],
              "reference": {
                "fields": [
                  "id_grupo_matserv"
                ],
                "resource": "dm_grupo_matserv"
              }
            },
            {
              "fields": [
                "id_contratado"
              ],
              "reference": {
                "fields": [
                  "id_contratado"
                ],
                "resource": "dm_contratado"
              }
            },
            {
              "fields": [
                "id_procedimento"
              ],
              "reference": {
                "fields": [
                  "id_procedimento"
                ],
                "resource": "dm_procedimento"
              }
            }
          ]
        },
        "sources": [
          {
            "title": "Tabela origem no schema AGE7 no banco de dados do Portal da Transparência",
            "table": "ft_compras"
          }
        ],
        "format": "csv",
        "mediatype": "text/csv",
        "encoding": "utf-8-sig",
        "dialect": {
          "delimiter": ";"
        },
        "profile": "tabular-data-resource",
        "scheme": "file",
        "hashing": "md5",
        "compression": "gz",
        "stats": {
          "hash": "200aa9428c393238ebcda39dcb3f07d1",
          "bytes": 57876041,
          "fields": 27,
          "rows": 1898197
        }
      },
      "time": 402.122,
      "scope": [
        "hash-count-error",
        "byte-count-error",
        "field-count-error",
        "row-count-error",
        "blank-header",
        "extra-label",
        "missing-label",
        "blank-label",
        "duplicate-label",
        "incorrect-label",
        "blank-row",
        "primary-key-error",
        "foreign-key-error",
        "extra-cell",
        "missing-cell",
        "type-error",
        "constraint-error",
        "unique-error"
      ],
      "partial": false,
      "errors": [
        {
          "cells": [
            "43536",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "33700",
            "1",
            "10",
            "501",
            "5144",
            "7682",
            "381283",
            "77969",
            "148",
            "1831307",
            "2586",
            "2081",
            "2022",
            "2022-11-04",
            "450.0000",
            "30.2800",
            "13626.00",
            "11.8500",
            "5332.50",
            "5332.50"
          ],
          "rowNumber": 1812606,
          "rowPosition": 1812607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77969\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812607\" violates the foreign key: for \"id_contrato\": values \"77969\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43536",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "33700",
            "1",
            "10",
            "501",
            "1",
            "53838",
            "381283",
            "77969",
            "371",
            "1831307",
            "2586",
            "2081",
            "2022",
            "2022-11-04",
            "300.0000",
            "34.2500",
            "10275.00",
            "19.7500",
            "5925.00",
            "5925.00"
          ],
          "rowNumber": 1812607,
          "rowPosition": 1812608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77969\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812608\" violates the foreign key: for \"id_contrato\": values \"77969\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44052",
            "1",
            "1831020",
            "9",
            "1",
            "1",
            "66",
            "55666",
            "1",
            "39",
            "130",
            "20370",
            "151133",
            "372810",
            "77956",
            "889",
            "1831805",
            "3067",
            "2839",
            "2022",
            "2022-07-11",
            "0.0000",
            "294766.6800",
            "294766.68",
            "294766.6800",
            "294766.68",
            "294766.68"
          ],
          "rowNumber": 1812776,
          "rowPosition": 1812777,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77956\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1812777\" violates the foreign key: for \"id_contrato\": values \"77956\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831072",
            "73",
            "1",
            "1",
            "66",
            "64828",
            "1",
            "51",
            "374",
            "6880",
            "91230",
            "380841",
            "77962",
            "889",
            "1831362",
            "2545",
            "3372",
            "2022",
            "2022-10-26",
            "0.0000",
            "12060.0000",
            "12060.00",
            "12619.2600",
            "12619.26",
            "12619.26"
          ],
          "rowNumber": 1813397,
          "rowPosition": 1813398,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77962\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813398\" violates the foreign key: for \"id_contrato\": values \"77962\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43572",
            "4",
            "1831072",
            "73",
            "1",
            "1",
            "66",
            "64828",
            "1",
            "51",
            "374",
            "6880",
            "115494",
            "380841",
            "77962",
            "889",
            "1831362",
            "2545",
            "3372",
            "2022",
            "2022-10-26",
            "0.0000",
            "8830.0000",
            "8830.00",
            "7548.7300",
            "7548.73",
            "7548.73"
          ],
          "rowNumber": 1813398,
          "rowPosition": 1813399,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77962\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1813399\" violates the foreign key: for \"id_contrato\": values \"77962\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43507",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "24913",
            "1",
            "77",
            "272",
            "4333",
            "91497",
            "378633",
            "77959",
            "889",
            "1831726",
            "2666",
            "2838",
            "2022",
            "2022-09-26",
            "0.0000",
            "34361.6600",
            "34361.66",
            "26862.0000",
            "26862.00",
            "26862.00"
          ],
          "rowNumber": 1814241,
          "rowPosition": 1814242,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77959\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814242\" violates the foreign key: for \"id_contrato\": values \"77959\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43507",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "24913",
            "1",
            "77",
            "272",
            "12261",
            "91501",
            "378633",
            "77959",
            "889",
            "1831726",
            "2666",
            "2838",
            "2022",
            "2022-09-26",
            "0.0000",
            "1931.8000",
            "1931.80",
            "1512.0000",
            "1512.00",
            "1512.00"
          ],
          "rowNumber": 1814242,
          "rowPosition": 1814243,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77959\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814243\" violates the foreign key: for \"id_contrato\": values \"77959\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43507",
            "4",
            "1831102",
            "89",
            "1",
            "1",
            "66",
            "24913",
            "1",
            "77",
            "272",
            "4333",
            "139637",
            "378633",
            "77959",
            "889",
            "1831726",
            "2666",
            "2838",
            "2022",
            "2022-09-26",
            "0.0000",
            "12018.7000",
            "12018.70",
            "11526.0000",
            "11526.00",
            "11526.00"
          ],
          "rowNumber": 1814696,
          "rowPosition": 1814697,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77959\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1814697\" violates the foreign key: for \"id_contrato\": values \"77959\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "398",
            "10451",
            "22166",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "1000.0000",
            "15.8500",
            "15850.00",
            "12.6000",
            "12600.00",
            "12600.00"
          ],
          "rowNumber": 1816358,
          "rowPosition": 1816359,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816359\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "63",
            "124",
            "13136",
            "85964",
            "381245",
            "77954",
            "940",
            "1831330",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "3.0000",
            "16.5000",
            "49.50",
            "16.0000",
            "48.00",
            "48.00"
          ],
          "rowNumber": 1816359,
          "rowPosition": 1816360,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816360\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "398",
            "10545",
            "143284",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "725.0000",
            "10.6100",
            "7692.25",
            "3.6000",
            "2610.00",
            "2610.00"
          ],
          "rowNumber": 1816360,
          "rowPosition": 1816361,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816361\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "722",
            "10838",
            "7157",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "14.0000",
            "12.5900",
            "176.19",
            "5.0000",
            "70.00",
            "70.00"
          ],
          "rowNumber": 1816361,
          "rowPosition": 1816362,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816362\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "733",
            "21757",
            "177352",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "30.0000",
            "36.5700",
            "1096.95",
            "18.0000",
            "540.00",
            "540.00"
          ],
          "rowNumber": 1816362,
          "rowPosition": 1816363,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816363\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "10",
            "312",
            "5162",
            "56426",
            "381245",
            "77954",
            "874",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "50.0000",
            "15.9100",
            "795.25",
            "14.4000",
            "720.00",
            "720.00"
          ],
          "rowNumber": 1816363,
          "rowPosition": 1816364,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816364\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "398",
            "21744",
            "175964",
            "381245",
            "77954",
            "1544",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "210.0000",
            "34.7300",
            "7292.25",
            "21.5000",
            "4515.00",
            "4515.00"
          ],
          "rowNumber": 1816364,
          "rowPosition": 1816365,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816365\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "722",
            "9",
            "83193",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "110.0000",
            "2.8300",
            "311.30",
            "0.5000",
            "55.00",
            "55.00"
          ],
          "rowNumber": 1816365,
          "rowPosition": 1816366,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816366\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "733",
            "10947",
            "97049",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "58.0000",
            "23.9100",
            "1386.78",
            "12.0000",
            "696.00",
            "696.00"
          ],
          "rowNumber": 1816366,
          "rowPosition": 1816367,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816367\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "733",
            "13845",
            "159374",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "10.0000",
            "26.9600",
            "269.60",
            "12.0000",
            "120.00",
            "120.00"
          ],
          "rowNumber": 1816367,
          "rowPosition": 1816368,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816368\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "398",
            "6801",
            "143286",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "130.0000",
            "5.0000",
            "649.35",
            "3.0000",
            "390.00",
            "390.00"
          ],
          "rowNumber": 1816368,
          "rowPosition": 1816369,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816369\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "722",
            "5784",
            "37990",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "100.0000",
            "6.9300",
            "692.50",
            "4.0000",
            "400.00",
            "400.00"
          ],
          "rowNumber": 1816369,
          "rowPosition": 1816370,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816370\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "722",
            "2757",
            "143295",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "30.0000",
            "2.6000",
            "78.00",
            "2.0000",
            "60.00",
            "60.00"
          ],
          "rowNumber": 1816370,
          "rowPosition": 1816371,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816371\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "722",
            "2757",
            "7478",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "60.0000",
            "10.2900",
            "617.10",
            "6.0000",
            "360.00",
            "360.00"
          ],
          "rowNumber": 1816371,
          "rowPosition": 1816372,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816372\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "722",
            "21706",
            "174098",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "10.0000",
            "0.9400",
            "9.40",
            "0.3600",
            "3.60",
            "3.60"
          ],
          "rowNumber": 1816372,
          "rowPosition": 1816373,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816373\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "53",
            "398",
            "13101",
            "80424",
            "381245",
            "77954",
            "889",
            "1831301",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "52.0000",
            "27.2400",
            "1416.22",
            "3.0000",
            "156.00",
            "156.00"
          ],
          "rowNumber": 1816373,
          "rowPosition": 1816374,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816374\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43563",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "2376",
            "1",
            "19",
            "628",
            "15990",
            "107124",
            "381245",
            "77954",
            "936",
            "1831992",
            "2657",
            "3043",
            "2022",
            "2022-11-04",
            "32.0000",
            "8.1700",
            "261.28",
            "8.0000",
            "256.00",
            "256.00"
          ],
          "rowNumber": 1816374,
          "rowPosition": 1816375,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1816375\" violates the foreign key: for \"id_contrato\": values \"77954\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43561",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "203",
            "27496",
            "1",
            "30",
            "173",
            "14875",
            "110770",
            "380771",
            "77963",
            "889",
            "1831355",
            "2670",
            "3043",
            "2022",
            "2022-10-25",
            "0.0000",
            "17601.5100",
            "17601.51",
            "12449.9200",
            "12449.92",
            "12449.92"
          ],
          "rowNumber": 1818274,
          "rowPosition": 1818275,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77963\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1818275\" violates the foreign key: for \"id_contrato\": values \"77963\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "58779",
            "1",
            "77",
            "479",
            "20171",
            "93519",
            "381403",
            "77968",
            "889",
            "1831808",
            "2602",
            "3043",
            "2022",
            "2022-11-08",
            "0.0000",
            "48139.0000",
            "48139.00",
            "48139.0000",
            "48139.00",
            "48139.00"
          ],
          "rowNumber": 1821009,
          "rowPosition": 1821010,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77968\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821010\" violates the foreign key: for \"id_contrato\": values \"77968\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "4",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "58779",
            "1",
            "77",
            "479",
            "20171",
            "93519",
            "381403",
            "77968",
            "889",
            "1831808",
            "2602",
            "3043",
            "2022",
            "2022-11-08",
            "0.0000",
            "71859.0000",
            "71859.00",
            "71859.0000",
            "71859.00",
            "71859.00"
          ],
          "rowNumber": 1821010,
          "rowPosition": 1821011,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77968\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1821011\" violates the foreign key: for \"id_contrato\": values \"77968\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43555",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "19474",
            "1",
            "58",
            "519",
            "9253",
            "196028",
            "381135",
            "77955",
            "889",
            "1831386",
            "2813",
            "2081",
            "2022",
            "2022-11-03",
            "2.0000",
            "23014.1500",
            "46028.30",
            "18000.0000",
            "36000.00",
            "36000.00"
          ],
          "rowNumber": 1825015,
          "rowPosition": 1825016,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77955\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1825016\" violates the foreign key: for \"id_contrato\": values \"77955\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "80",
            "308",
            "5792",
            "122500",
            "381329",
            "77965",
            "305",
            "1831306",
            "2994",
            "2081",
            "2022",
            "2022-11-07",
            "26.0000",
            "188.0000",
            "4888.00",
            "153.8000",
            "3998.80",
            "3998.80"
          ],
          "rowNumber": 1827753,
          "rowPosition": 1827754,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77965\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827754\" violates the foreign key: for \"id_contrato\": values \"77965\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43541",
            "4",
            "1831059",
            "57",
            "1",
            "1",
            "501",
            "69417",
            "1",
            "46",
            "123",
            "3039",
            "134212",
            "381329",
            "77965",
            "996",
            "1831340",
            "3084",
            "2081",
            "2022",
            "2022-11-07",
            "6000.0000",
            "7.3000",
            "43800.00",
            "6.4100",
            "38460.00",
            "38460.00"
          ],
          "rowNumber": 1827754,
          "rowPosition": 1827755,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77965\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1827755\" violates the foreign key: for \"id_contrato\": values \"77965\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43543",
            "4",
            "1831095",
            "96",
            "1",
            "1",
            "66",
            "60548",
            "1",
            "89",
            "778",
            "11092",
            "361338",
            "380805",
            "77966",
            "889",
            "1831330",
            "2746",
            "3955",
            "2022",
            "2022-10-25",
            "1.0000",
            "60083.0000",
            "60083.00",
            "60083.0000",
            "60083.00",
            "60083.00"
          ],
          "rowNumber": 1831801,
          "rowPosition": 1831802,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77966\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1831802\" violates the foreign key: for \"id_contrato\": values \"77966\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43558",
            "4",
            "1831034",
            "21",
            "1",
            "1",
            "66",
            "17593",
            "1",
            "54",
            "502",
            "15252",
            "154479",
            "380948",
            "77957",
            "889",
            "1831296",
            "2944",
            "1760",
            "2022",
            "2022-10-27",
            "240.0000",
            "805.0000",
            "193200.00",
            "751.6000",
            "180384.00",
            "180384.00"
          ],
          "rowNumber": 1854463,
          "rowPosition": 1854464,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77957\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1854464\" violates the foreign key: for \"id_contrato\": values \"77957\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43557",
            "2",
            "1831079",
            "76",
            "1",
            "1",
            "66",
            "31915",
            "1",
            "39",
            "130",
            "20348",
            "98672",
            "380202",
            "77960",
            "889",
            "1831812",
            "3135",
            "2046",
            "2022",
            "2022-10-18",
            "0.0000",
            "11000.0000",
            "11000.00",
            "11000.0000",
            "11000.00",
            "11000.00"
          ],
          "rowNumber": 1872623,
          "rowPosition": 1872624,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77960\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1872624\" violates the foreign key: for \"id_contrato\": values \"77960\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "71964",
            "1",
            "53",
            "722",
            "5784",
            "37991",
            "379825",
            "77970",
            "889",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "420.0000",
            "11.0000",
            "4620.00",
            "7.8500",
            "3297.00",
            "3297.00"
          ],
          "rowNumber": 1880271,
          "rowPosition": 1880272,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77970\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880272\" violates the foreign key: for \"id_contrato\": values \"77970\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "19011",
            "1",
            "53",
            "722",
            "109",
            "75531",
            "379825",
            "77952",
            "893",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "5.0000",
            "8.5000",
            "42.50",
            "7.1500",
            "35.75",
            "35.75"
          ],
          "rowNumber": 1880272,
          "rowPosition": 1880273,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880273\" violates the foreign key: for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "19011",
            "1",
            "53",
            "733",
            "8016",
            "83456",
            "379825",
            "77952",
            "889",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "12.0000",
            "3.5400",
            "42.48",
            "3.3000",
            "39.60",
            "39.60"
          ],
          "rowNumber": 1880273,
          "rowPosition": 1880274,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880274\" violates the foreign key: for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "19011",
            "1",
            "53",
            "398",
            "21744",
            "175963",
            "379825",
            "77952",
            "1544",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "300.0000",
            "26.0000",
            "7800.00",
            "22.6000",
            "6780.00",
            "6780.00"
          ],
          "rowNumber": 1880274,
          "rowPosition": 1880275,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880275\" violates the foreign key: for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "19011",
            "1",
            "53",
            "722",
            "109",
            "8894",
            "379825",
            "77952",
            "893",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "5.0000",
            "4.4900",
            "22.45",
            "4.4500",
            "22.25",
            "22.25"
          ],
          "rowNumber": 1880275,
          "rowPosition": 1880276,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880276\" violates the foreign key: for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "19011",
            "1",
            "53",
            "722",
            "15937",
            "3424",
            "379825",
            "77952",
            "940",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "10.0000",
            "42.5200",
            "425.15",
            "39.2000",
            "392.00",
            "392.00"
          ],
          "rowNumber": 1880276,
          "rowPosition": 1880277,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880277\" violates the foreign key: for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43571",
            "14",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "19011",
            "1",
            "53",
            "722",
            "18379",
            "83409",
            "379825",
            "77952",
            "944",
            "1831301",
            "2657",
            "1858",
            "2022",
            "2022-10-13",
            "10.0000",
            "27.8700",
            "278.65",
            "27.2000",
            "272.00",
            "272.00"
          ],
          "rowNumber": 1880277,
          "rowPosition": 1880278,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1880278\" violates the foreign key: for \"id_contrato\": values \"77952\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "32",
            "100",
            "19412",
            "31314",
            "379877",
            "77964",
            "189",
            "1831400",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "30.0000",
            "23.9100",
            "717.30",
            "13.5000",
            "405.00",
            "405.00"
          ],
          "rowNumber": 1887591,
          "rowPosition": 1887592,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887592\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "13212",
            "28952",
            "379877",
            "77964",
            "889",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "40.0000",
            "11.0000",
            "440.00",
            "2.8700",
            "114.80",
            "114.80"
          ],
          "rowNumber": 1887598,
          "rowPosition": 1887599,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887599\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "2814",
            "8990",
            "379877",
            "77964",
            "1750",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "36.0000",
            "20.3000",
            "730.80",
            "5.8300",
            "209.88",
            "209.88"
          ],
          "rowNumber": 1887605,
          "rowPosition": 1887606,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887606\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "2814",
            "126065",
            "379877",
            "77964",
            "1750",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "36.0000",
            "16.7900",
            "604.44",
            "8.1900",
            "294.84",
            "294.84"
          ],
          "rowNumber": 1887606,
          "rowPosition": 1887607,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887607\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "2814",
            "3333",
            "379877",
            "77964",
            "1750",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "36.0000",
            "10.6000",
            "381.60",
            "4.5200",
            "162.72",
            "162.72"
          ],
          "rowNumber": 1887607,
          "rowPosition": 1887608,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887608\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "2814",
            "9339",
            "379877",
            "77964",
            "1750",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "36.0000",
            "6.2500",
            "225.00",
            "3.2500",
            "117.00",
            "117.00"
          ],
          "rowNumber": 1887608,
          "rowPosition": 1887609,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887609\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "15976",
            "29482",
            "379877",
            "77964",
            "889",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "15.0000",
            "3.2000",
            "48.00",
            "2.0000",
            "30.00",
            "30.00"
          ],
          "rowNumber": 1887610,
          "rowPosition": 1887611,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887611\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "43514",
            "4",
            "1831028",
            "25",
            "1",
            "1",
            "855",
            "69799",
            "1",
            "52",
            "757",
            "15976",
            "32632",
            "379877",
            "77964",
            "889",
            "1831189",
            "2658",
            "1858",
            "2022",
            "2022-10-14",
            "15.0000",
            "15.4700",
            "232.05",
            "7.0000",
            "105.00",
            "105.00"
          ],
          "rowNumber": 1887614,
          "rowPosition": 1887615,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1887615\" violates the foreign key: for \"id_contrato\": values \"77964\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44419",
            "17",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "58921",
            "1",
            "77",
            "73",
            "7572",
            "143155",
            "381850",
            "77971",
            "889",
            "1831761",
            "2872",
            "3043",
            "2022",
            "2022-11-11",
            "0.0000",
            "1064.0000",
            "1064.00",
            "1064.0000",
            "1064.00",
            "1064.00"
          ],
          "rowNumber": 1888025,
          "rowPosition": 1888026,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77971\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888026\" violates the foreign key: for \"id_contrato\": values \"77971\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44420",
            "17",
            "1831084",
            "81",
            "1",
            "1",
            "66",
            "59153",
            "1",
            "39",
            "834",
            "21966",
            "378745",
            "381835",
            "77972",
            "889",
            "1831739",
            "3067",
            "1859",
            "2022",
            "2022-11-11",
            "0.0000",
            "199764.0000",
            "199764.00",
            "199764.0000",
            "199764.00",
            "199764.00"
          ],
          "rowNumber": 1888026,
          "rowPosition": 1888027,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77972\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1888027\" violates the foreign key: for \"id_contrato\": values \"77972\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "142",
            "20473",
            "112757",
            "380648",
            "77953",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "13.0000",
            "162.3700",
            "2110.81",
            "162.3700",
            "2110.81",
            "2110.81"
          ],
          "rowNumber": 1892651,
          "rowPosition": 1892652,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77953\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892652\" violates the foreign key: for \"id_contrato\": values \"77953\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "544",
            "13338",
            "164205",
            "380648",
            "77953",
            "1292",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "10500.0000",
            "1.7900",
            "18795.00",
            "1.7900",
            "18795.00",
            "18795.00"
          ],
          "rowNumber": 1892653,
          "rowPosition": 1892654,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77953\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892654\" violates the foreign key: for \"id_contrato\": values \"77953\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "22394",
            "1",
            "37",
            "142",
            "20473",
            "131156",
            "380648",
            "77953",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "1.0000",
            "162.3700",
            "162.37",
            "162.3700",
            "162.37",
            "162.37"
          ],
          "rowNumber": 1892655,
          "rowPosition": 1892656,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77953\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1892656\" violates the foreign key: for \"id_contrato\": values \"77953\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "18049",
            "1",
            "60",
            "326",
            "19276",
            "182060",
            "380693",
            "77967",
            "889",
            "1831952",
            "2742",
            "3043",
            "2022",
            "2022-10-24",
            "1.0000",
            "7200.0000",
            "7200.00",
            "7200.0000",
            "7200.00",
            "7200.00"
          ],
          "rowNumber": 1893451,
          "rowPosition": 1893452,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77967\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893452\" violates the foreign key: for \"id_contrato\": values \"77967\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "18049",
            "1",
            "60",
            "652",
            "9816",
            "166106",
            "380653",
            "77973",
            "889",
            "1831952",
            "2995",
            "3043",
            "2022",
            "2022-10-24",
            "4.0000",
            "250.2200",
            "1000.88",
            "250.2200",
            "1000.88",
            "1000.88"
          ],
          "rowNumber": 1893456,
          "rowPosition": 1893457,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77973\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893457\" violates the foreign key: for \"id_contrato\": values \"77973\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "37",
            "17",
            "2018",
            "130544",
            "380669",
            "77961",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "50.0000",
            "161.9100",
            "8095.50",
            "161.9100",
            "8095.50",
            "8095.50"
          ],
          "rowNumber": 1893464,
          "rowPosition": 1893465,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893465\" violates the foreign key: for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "60",
            "85",
            "7177",
            "152784",
            "380669",
            "77961",
            "889",
            "1831952",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "1.0000",
            "1993.2300",
            "1993.23",
            "1993.2300",
            "1993.23",
            "1993.23"
          ],
          "rowNumber": 1893465,
          "rowPosition": 1893466,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893466\" violates the foreign key: for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "19",
            "628",
            "16622",
            "169567",
            "380669",
            "77961",
            "889",
            "1831992",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "50.0000",
            "236.2800",
            "11814.00",
            "236.2800",
            "11814.00",
            "11814.00"
          ],
          "rowNumber": 1893466,
          "rowPosition": 1893467,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893467\" violates the foreign key: for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44402",
            "15",
            "1831094",
            "95",
            "1",
            "1",
            "66",
            "23230",
            "1",
            "19",
            "611",
            "20502",
            "169576",
            "380669",
            "77961",
            "889",
            "1831992",
            "2927",
            "3043",
            "2022",
            "2022-10-24",
            "10.0000",
            "627.8600",
            "6278.60",
            "627.8600",
            "6278.60",
            "6278.60"
          ],
          "rowNumber": 1893467,
          "rowPosition": 1893468,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1893468\" violates the foreign key: for \"id_contrato\": values \"77961\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        },
        {
          "cells": [
            "44403",
            "1",
            "1831103",
            "94",
            "1",
            "1",
            "66",
            "32287",
            "1",
            "9",
            "576",
            "1923",
            "93139",
            "381672",
            "77958",
            "889",
            "1831678",
            "2738",
            "2212",
            "2022",
            "2022-11-10",
            "0.0000",
            "189972.5700",
            "189972.57",
            "189972.5700",
            "189972.57",
            "189972.57"
          ],
          "rowNumber": 1898074,
          "rowPosition": 1898075,
          "code": "foreign-key-error",
          "name": "ForeignKey Error",
          "tags": [
            "#table",
            "#row"
          ],
          "note": "for \"id_contrato\": values \"77958\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "message": "Row at position \"1898075\" violates the foreign key: for \"id_contrato\": values \"77958\" not found in the lookup table \"dm_contrato\" as \"id_contrato\"",
          "description": "Values in the foreign key fields should exist in the reference table"
        }
      ],
      "stats": {
        "errors": 61
      },
      "valid": false
    }
  ],
  "stats": {
    "errors": 61,
    "tasks": 1
  },
  "valid": false
}